# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Develop Merge

on:
  pull_request:
    branches: [develop]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build container with python ${{ matrix.python-version }}
        run: docker build --build-arg "pyver=${{ matrix.python-version }}" -f ./.github/Dockerfile -t pipelime:latest .
      - name: Lint with flake8 in container 1/2
        run: |
          # stop the build if there are Python syntax errors or undefined names
          docker run --rm pipelime flake8 pipelime --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Lint with flake8 in container 2/2
        run: |
          # stop the build if there are Python syntax errors or undefined names
          docker run --rm pipelime flake8 pipelime --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run tests in container
        run: docker run --rm pipelime
